spring:
  application:
    name: ramengo
  datasource:
    url: jdbc:postgresql://localhost:5432/ramengo
    username: postgres
    password: topsecret
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

api:
  key:
    header: x-api-key
    value: ZtVdh8XQ2U8pWI2gmZ7f796Vh8GllXoN7mr0djNf
